"""empty message

Revision ID: 0cb0781d36ec
Revises: 6072354a7da8
Create Date: 2025-06-16 14:36:36.751766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb0781d36ec'
down_revision = '6072354a7da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_pizzas')
    op.drop_table('restaurants')
    op.drop_table('pizzas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pizzas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ingredients', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pizzas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('restaurant_pizzas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], name='restaurant_pizzas_pizza_id_fkey'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='restaurant_pizzas_restaurant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='restaurant_pizzas_pkey')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='restaurants_pkey')
    )
    # ### end Alembic commands ###
